# Generated by Django 5.2.16 on 2026-09-23 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_payment_indeterminate_and_vandar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledgerentry',
            options={'ordering': ['-created_at'], 'verbose_name': 'سند دفترکل', 'verbose_name_plural': 'اسناد دفترکل'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'پرداخت', 'verbose_name_plural': 'پرداخت ها'},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['-created_at'], 'verbose_name': 'کیف پول', 'verbose_name_plural': 'کیف پول ها'},
        ),
        migrations.AlterModelOptions(
            name='withdrawalrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'درخواست برداشت', 'verbose_name_plural': 'درخواست های برداشت'},
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='balance_after',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='موجودی پس از تراکنش'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='direction',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=16, verbose_name='به جهت'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('appointment_hold', 'Appointment hold'), ('appointment_capture', 'Appointment capture'), ('refund', 'Refund'), ('forfeit', 'Forfeit'), ('workshop_purchase', 'Workshop purchase'), ('withdrawal', 'Withdrawal'), ('withdrawal_reversal', 'Withdrawal reversal'), ('adjustment', 'Adjustment')], max_length=32, verbose_name='نوع سند'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='idempotency_key',
            field=models.CharField(max_length=64, unique=True, verbose_name='کلید یکتایی'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='reference',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='مرجع'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finance.wallet', verbose_name='کیف پول'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ledger_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='finance.ledgerentry', verbose_name='سند دفترکل'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='فراداده'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('manual', 'Manual / reception'), ('sep', 'SEP (Saman Electronic Payment)'), ('vandar', 'Vandar'), ('gateway', 'Generic gateway')], default='vandar', max_length=16, verbose_name='درگاه'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider_ref',
            field=models.CharField(blank=True, db_index=True, max_length=128, verbose_name='شناسه درگاه'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(blank=True, max_length=64, verbose_name='بابت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('indeterminate', 'Indeterminate'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=16, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Cached IRR balance. Ledger is the source of truth.', max_digits=12, verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='bank_details',
            field=models.JSONField(default=dict, verbose_name='اطلاعات بانکی'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='ledger_finalize_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.ledgerentry', verbose_name='سند نهایی'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='ledger_hold_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.ledgerentry', verbose_name='سند مسدودی'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals_processed', to=settings.AUTH_USER_MODEL, verbose_name='پردازش\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='دلیل رد'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], db_index=True, default='pending', max_length=16, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='ticket_reference',
            field=models.CharField(blank=True, help_text='Opaque ref e.g. psy.ticket:55 — no FK into domain apps.', max_length=64, verbose_name='مرجع تیکت'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='finance.wallet', verbose_name='کیف پول'),
        ),
    ]
