# Generated by Django 5.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_vandar_provider_and_indeterminate_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledgerentry",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit"),
                    ("appointment_hold", "Appointment hold"),
                    ("appointment_capture", "Appointment capture"),
                    ("refund", "Refund"),
                    ("forfeit", "Forfeit"),
                    ("workshop_purchase", "Workshop purchase"),
                    ("shop_purchase", "Shop purchase"),
                    ("withdrawal", "Withdrawal"),
                    ("withdrawal_reversal", "Withdrawal reversal"),
                    ("adjustment", "Adjustment"),
                ],
                max_length=32,
                verbose_name="نوع سند",
            ),
        ),
    ]
