# Generated by Django 5.2.16 on 2026-08-13 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psy_institute', '0003_appointment_meeting_link'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointmentslot',
            name='psy_slot_exclude_overlapping',
        ),
    ]
