# Generated by Django 5.2.16 on 2026-08-13 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psy_institute', '0004_remove_appointmentslot_psy_slot_exclude_overlapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='banner_image',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='workshop',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workshops', to='psy_institute.therapistprofile'),
        ),
        migrations.AddField(
            model_name='workshopenrollment',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshopenrollment',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workshopenrollment',
            name='deposit_ledger_ref',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='workshopenrollment',
            name='hold_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshopenrollment',
            name='price_snapshot',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='workshopenrollment',
            name='refund_ledger_ref',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
