# Generated by Django 5.2.16 on 2026-08-15 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psy_institute', '0005_workshop_instructor_banner_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='body_md',
            field=models.TextField(blank=True, help_text='Long-form Markdown introduction for the detail page.'),
        ),
        migrations.CreateModel(
            name='WorkshopSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('meeting_url', models.URLField(blank=True, max_length=500)),
                ('recording_url', models.URLField(blank=True, max_length=500)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='psy_institute.workshop')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('pdf', 'PDF'), ('slides', 'Slides'), ('other', 'Other')], default='other', max_length=16)),
                ('file_url', models.URLField(blank=True, max_length=500)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='psy_institute.workshop')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='psy_institute.workshopsession')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopSessionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_progress', to='psy_institute.workshopenrollment')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_rows', to='psy_institute.workshopsession')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workshopsession',
            index=models.Index(fields=['workshop', 'sort_order'], name='psy_institu_worksho_c7f9bc_idx'),
        ),
        migrations.AddIndex(
            model_name='workshopresource',
            index=models.Index(fields=['workshop', 'sort_order'], name='psy_institu_worksho_13e171_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workshopsessionprogress',
            unique_together={('enrollment', 'session')},
        ),
    ]
