# Generated by Django 5.2.16 on 2026-10-09 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psy_institute', '0015_therapistprofile_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبدهای خرید',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
            ],
            options={
                'verbose_name': 'آیتم سبد',
                'verbose_name_plural': 'آیتم\u200cهای سبد',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='کد')),
                ('kind', models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed amount')], max_length=16, verbose_name='نوع تخفیف')),
                ('value', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مقدار')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='سقف تخفیف (ریال)')),
                ('min_order_total', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='حداقل مبلغ سفارش (ریال)')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='شروع')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='پایان')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='سقف استفاده کل')),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, verbose_name='سقف استفاده هر مراجع')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'مصرف کد تخفیف',
                'verbose_name_plural': 'مصرف\u200cهای کد تخفیف',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='شماره سفارش')),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment'), ('paid', 'Paid'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('refunded', 'Refunded')], db_index=True, default='pending_payment', max_length=20, verbose_name='وضعیت')),
                ('requires_shipping', models.BooleanField(default=False, verbose_name='نیاز به ارسال')),
                ('shipping_full_name', models.CharField(blank=True, max_length=120, verbose_name='نام گیرنده')),
                ('shipping_phone', models.CharField(blank=True, max_length=32, verbose_name='تلفن')),
                ('shipping_province', models.CharField(blank=True, max_length=64, verbose_name='استان')),
                ('shipping_city', models.CharField(blank=True, max_length=64, verbose_name='شهر')),
                ('shipping_address', models.TextField(blank=True, verbose_name='نشانی')),
                ('shipping_postal_code', models.CharField(blank=True, max_length=20, verbose_name='کد پستی')),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='جمع جزء (ریال)')),
                ('discount_total', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='تخفیف (ریال)')),
                ('shipping_fee', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='هزینه ارسال (ریال)')),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مبلغ قابل پرداخت (ریال)')),
                ('coupon_code', models.CharField(blank=True, max_length=40, verbose_name='کد تخفیف')),
                ('payment_ref', models.CharField(blank=True, max_length=64, verbose_name='مرجع پرداخت')),
                ('deposit_ledger_ref', models.CharField(blank=True, max_length=64, verbose_name='سند برداشت')),
                ('refund_ledger_ref', models.CharField(blank=True, max_length=64, verbose_name='سند بازگشت')),
                ('hold_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='انقضای مهلت پرداخت')),
                ('gateway_payment_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='شناسه پرداخت درگاه')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
                ('tracking_code', models.CharField(blank=True, max_length=64, verbose_name='کد رهگیری')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان لغو')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='دلیل لغو')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت مدیر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('kind', models.CharField(max_length=16, verbose_name='نوع')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت واحد (ریال)')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('line_total', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='جمع ردیف (ریال)')),
            ],
            options={
                'verbose_name': 'قلم سفارش',
                'verbose_name_plural': 'اقلام سفارش',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='نامک')),
                ('kind', models.CharField(choices=[('physical', 'Physical'), ('digital', 'Digital')], default='physical', max_length=16, verbose_name='نوع')),
                ('description', models.TextField(blank=True, verbose_name='خلاصه')),
                ('body_md', models.TextField(blank=True, verbose_name='توضیحات')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت (ریال)')),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='قیمت قبل از تخفیف (ریال)')),
                ('image', models.ImageField(blank=True, max_length=500, upload_to='psy/shop/products/', verbose_name='تصویر')),
                ('digital_file', models.FileField(blank=True, max_length=500, upload_to='psy/shop/files/', verbose_name='فایل دیجیتال')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('is_available', models.BooleanField(default=True, verbose_name='قابل خرید')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('name', models.CharField(max_length=120, verbose_name='نام')),
                ('slug', models.SlugField(unique=True, verbose_name='نامک')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی فروشگاه',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای فروشگاه',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop_cart', to='psy_institute.patientprofile', verbose_name='مراجع'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='psy_institute.cart', verbose_name='سبد'),
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='psy_institute.coupon', verbose_name='کد تخفیف'),
        ),
        migrations.AddField(
            model_name='couponredemption',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='psy_institute.coupon', verbose_name='کد تخفیف'),
        ),
        migrations.AddField(
            model_name='couponredemption',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_redemptions', to='psy_institute.patientprofile', verbose_name='مراجع'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='psy_institute.coupon', verbose_name='کد تخفیف'),
        ),
        migrations.AddField(
            model_name='order',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_orders', to='psy_institute.patientprofile', verbose_name='مراجع'),
        ),
        migrations.AddField(
            model_name='couponredemption',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemption', to='psy_institute.order', verbose_name='سفارش'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='psy_institute.order', verbose_name='سفارش'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='psy_institute.product', verbose_name='محصول'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='psy_institute.product', verbose_name='محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='psy_institute.productcategory', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product'), name='psy_cart_item_unique_product'),
        ),
    ]
