# Generated by Django 5.2.16 on 2026-09-13 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('phone', models.CharField(max_length=32, verbose_name='شماره')),
                ('purpose', models.CharField(choices=[('otp_register', 'OTP ثبت\u200cنام'), ('otp_password_reset', 'OTP بازیابی رمز'), ('appointment', 'نوبت'), ('admin_manual', 'ارسال دستی ادمین')], max_length=32, verbose_name='هدف')),
                ('body', models.TextField(verbose_name='متن')),
                ('provider_sms_id', models.CharField(blank=True, max_length=128, verbose_name='شناسه پیامک')),
                ('status', models.CharField(choices=[('queued', 'در صف'), ('sent', 'ارسال شده'), ('failed', 'ناموفق'), ('skipped_no_phone', 'بدون شماره')], default='queued', max_length=32, verbose_name='وضعیت')),
                ('error', models.TextField(blank=True, verbose_name='خطا')),
                ('unique_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='شناسه یکتا')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پیامک',
                'verbose_name_plural': 'پیامک\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
