# Generated by Django 5.2.16 on 2026-09-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_sms_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('phone', models.CharField(db_index=True, max_length=32, verbose_name='شماره')),
                ('purpose', models.CharField(choices=[('otp_register', 'OTP ثبت\u200cنام'), ('otp_password_reset', 'OTP بازیابی رمز')], max_length=32, verbose_name='هدف')),
                ('code_hash', models.CharField(max_length=64, verbose_name='هش کد')),
                ('expires_at', models.DateTimeField(verbose_name='انقضا')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='تلاش')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='مصرف')),
            ],
            options={
                'verbose_name': 'چالش OTP',
                'verbose_name_plural': 'چالش\u200cهای OTP',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', 'purpose', '-created_at'], name='notificatio_phone_832e20_idx')],
            },
        ),
    ]
