# Generated by Django 5.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_otp_challenge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smsmessage",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("otp_register", "OTP ثبت\u200cنام"),
                    ("otp_password_reset", "OTP بازیابی رمز"),
                    ("appointment", "نوبت"),
                    ("shop", "فروشگاه"),
                    ("admin_manual", "ارسال دستی ادمین"),
                ],
                max_length=32,
                verbose_name="هدف",
            ),
        ),
    ]
